// <auto-generated />
using System;
using GestorDeGastos.Server.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestorDeGastosBS.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestorDeGastosBS.Data.Models.Empleado", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpleadoId"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpleadoId");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("GestorDeGastosBS.Data.Models.GastosGenerales", b =>
                {
                    b.Property<int>("GastoGeneralesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GastoGeneralesId"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("GastosMercanciaId")
                        .HasColumnType("int");

                    b.Property<int>("GastosMiscelaneoId")
                        .HasColumnType("int");

                    b.Property<int>("GastosProveedorId")
                        .HasColumnType("int");

                    b.Property<int>("Nominaid")
                        .HasColumnType("int");

                    b.HasKey("GastoGeneralesId");

                    b.HasIndex("GastosMercanciaId");

                    b.HasIndex("GastosMiscelaneoId");

                    b.HasIndex("GastosProveedorId");

                    b.HasIndex("Nominaid");

                    b.ToTable("GastosGenerales");
                });

            modelBuilder.Entity("GestorDeGastosBS.Data.Models.GastosMercancia", b =>
                {
                    b.Property<int>("GastosMercanciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GastosMercanciaId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descricción")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("Date");

                    b.Property<int>("MercanciaId")
                        .HasColumnType("int");

                    b.HasKey("GastosMercanciaId");

                    b.HasIndex("MercanciaId");

                    b.ToTable("GastosMercancias");
                });

            modelBuilder.Entity("GestorDeGastosBS.Data.Models.GastosMiscelaneo", b =>
                {
                    b.Property<int>("GastosMiscelaneoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GastosMiscelaneoId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descricción")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GastosMiscelaneoId");

                    b.ToTable("GastosMiscelaneos");
                });

            modelBuilder.Entity("GestorDeGastosBS.Data.Models.GastosProveedor", b =>
                {
                    b.Property<int>("GastosProveedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GastosProveedorId"));

                    b.Property<string>("Descricción")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Gastos")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("GastosProveedorId");

                    b.ToTable("GastosProveedores");
                });

            modelBuilder.Entity("GestorDeGastosBS.Data.Models.Mercancia", b =>
                {
                    b.Property<int>("MercanciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MercanciaId"));

                    b.Property<string>("MercanciaDescripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MercanciaNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int");

                    b.HasKey("MercanciaId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Mercancias");
                });

            modelBuilder.Entity("GestorDeGastosBS.Data.Models.Nomina", b =>
                {
                    b.Property<int>("Nominaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Nominaid"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.HasKey("Nominaid");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Nominas");
                });

            modelBuilder.Entity("GestorDeGastosBS.Data.Models.Proveedor", b =>
                {
                    b.Property<int>("ProveedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProveedorId"));

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProveedorId");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("GestorDeGastosBS.Data.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GestorDeGastosBS.Data.Models.GastosGenerales", b =>
                {
                    b.HasOne("GestorDeGastosBS.Data.Models.GastosMercancia", "GastosMercancia")
                        .WithMany()
                        .HasForeignKey("GastosMercanciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestorDeGastosBS.Data.Models.GastosMiscelaneo", "GastoMiscelaneo")
                        .WithMany()
                        .HasForeignKey("GastosMiscelaneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestorDeGastosBS.Data.Models.GastosProveedor", "GastosProveedor")
                        .WithMany()
                        .HasForeignKey("GastosProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestorDeGastosBS.Data.Models.Nomina", "Nomina")
                        .WithMany()
                        .HasForeignKey("Nominaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GastoMiscelaneo");

                    b.Navigation("GastosMercancia");

                    b.Navigation("GastosProveedor");

                    b.Navigation("Nomina");
                });

            modelBuilder.Entity("GestorDeGastosBS.Data.Models.GastosMercancia", b =>
                {
                    b.HasOne("GestorDeGastosBS.Data.Models.Mercancia", "Mercancia")
                        .WithMany()
                        .HasForeignKey("MercanciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mercancia");
                });

            modelBuilder.Entity("GestorDeGastosBS.Data.Models.Mercancia", b =>
                {
                    b.HasOne("GestorDeGastosBS.Data.Models.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("GestorDeGastosBS.Data.Models.Nomina", b =>
                {
                    b.HasOne("GestorDeGastosBS.Data.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });
#pragma warning restore 612, 618
        }
    }
}
